fix shell injection upon calling pdftk
I came across an error like this:

```
$ pdfoutliner toc.txt --inpdf "(John Smith) IRS.pdf" --outpdf '(John Smith) IRS new.pdf'
sh: 1: Syntax error: "(" unexpected
```

Again the argument is easily intepreted as a shell command, which easily causes trouble:

```
$ pdfoutliner toc.txt --inpdf "IRS.pdf" --outpdf '; exit'
Error: Failed to open output file:
   /home/user/
   No output created.
   No output created.
```

(I should be able to name a file '; exit' if I want to)